CREATE TABLE TB_PEDIDO (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	PRODUTO_ID BIGINT(20) NOT NULL,
	DESCRICAO VARCHAR(120) NOT NULL,
	QUANTIDADE INT(20) NOT NULL,
	DATA_COMPRA DATE NOT NULL,
	FOREIGN KEY (PRODUTO_ID) REFERENCES TB_PRODUTO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TB_PEDIDO (ID, PRODUTO_ID, DESCRICAO, QUANTIDADE, DATA_COMPRA) values (1, 1, 'Compra KIT Camiseta Tam M', 5, '2021-12-31');
INSERT INTO TB_PEDIDO (ID, PRODUTO_ID, DESCRICAO, QUANTIDADE, DATA_COMPRA) values (2, 4, 'Compra Bola Copa do Mundo 2002', 10, '2021-10-16');
INSERT INTO TB_PEDIDO (ID, PRODUTO_ID, DESCRICAO, QUANTIDADE, DATA_COMPRA) values (3, 2, 'Compra Regata Cleveland Cavaliers 19*20', 2, '2021-01-10');
